### Try/Except
```Python
try:
	print(10 / 0)
except ZeroDivisionError as e:
	print(type(e))
	# <class 'ZeroDivisionError'>
	print(e)  # division by zero
print('Continue)  # Continue...
```
> Можно использовать больше блоков `except`

Функция `print()` вызывает внутри функции магический метод `__str__`

Блок `else` - выполнится, если ошибок не возникло в блоке `try`
```Python
try:
	print(10 / 5)  # 2.0
except ZeroDivisionError as e:
	print(e)
except TypeError as e:
	print(e)
else:
	print("There was no error")  # Этот блок выполнится, если ошибок не возникло
	# There was no error

print('Continue...')  # Continue...
```

Блок `finally` - выполняется всегда после блока `try` или после блока `else` если он существует
```Python
try:
	print(10 / 5)  # 2.0
except ZeroDivisionError as e:
	print(e)
except TypeError as e:
	print(e)
else:
	print("There was no error")
	# There was no error
finally:
	print('Continue...')  # Continue...
```
> Если вы работаете с базой данных и Вам необходимо в блоке `try` подключиться к БД, выполнить определенные действия и потом отключиться от БД, то отключение от БД следует выполнять в блоке `finally`, независимо от того, возникла ошибка или нет. А вот в блоке `else` следует выполнять действия в случае если коммуникация с сервером прошла успешно и данные например были успешно переданы на сервер, и в блоке `else` мы можем выполнить другие действия с этими же данными, потому что мы знаем, что никаких ошибок в блоке `try` не возникло.

Любые ошибки в блоке `except`
```Python
try:
	print(10 / 0)
except Exception as e:
	print(e)  # division by zero
```
`Exception` - это родительский класс для таких классов как `ZeroDivisionError`, `TypeError`: они являются продолжением этого класса


**Создание ошибок**/Генерация ошибки с помощью `raise`
```Python
def divide_nums(a, b):
	if b == 0:
		raise ValueError("Second argument can't be 0")
	return a / b


try: 
	divide_nums(10, 0)
except ValueError as e:
	print(e)
	# Second argument can't be 0
print('Continue...')  # Continue...
```
> Это корректное поведение функции, т.е. все крайние случаи (side cases) рекомендуется обрабатывать внутри функции, если у вас происходит деление на какое то значение, и оно может быть 0, то лучше соответствующую обработку значений и генерацию ошибок добавить в функцию, а не делать это вне функции при её вызове


